spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:search_blog_db
    username: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath:sql/data-h2.sql
      platform: h2

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

feign:
  request-url:
    kakao: "https://dapi.kakao.com"
    naver: "https://openapi.naver.com"